### ISSUE TITLE
Allow exit immediately functionality on runcmd list

### ISSUE THREAD

**Issue by anmazzotti** [rancher/yip#133]
Currently all commands in a `runcmd`/`commands` list will be executed independently of each other. 
If the first command fails, all the others will still be executed.

Note that this is also the `cloud-init` behavior, so this should count as a `yip` only feature request.

The request is to make this behavior toggable in `yip`. For example by adding stage options:

```yaml
stages:
   my-stage:
     options:
       exitImmediately: true
     commands:
        - exit 2
        - echo "Success"
```

It would also be nice to enforce this value on all configs with an environment variable, so that it can be applied to `cloud-init` syntax configs as well.

This could help all those cases where a complex list of dependent commands needs to be executed, making the config itself more readable (instead of a giant pipe or an opaque bash script).

Could also help circumventing/mitigating issues like this one: https://github.com/rancher/cluster-api-provider-rke2/issues/221

Still this would differ from `cloud-init` behavior, so it should be used with care.
