### ISSUE TITLE
Implement network v2 config

### ISSUE THREAD

**Issue by frelon** [rancher/yip#82]
Reference found [here](https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v2.html)

Simple goal implementation:

```
network:
  version: 2
  ethernets:
    # opaque ID for physical interfaces, only referred to by other stanzas
    id0:
      match:
        macaddress: '00:11:22:33:44:55'
      dhcp4: true
```

Next steps would be adding bonding/vlans.
